
const apiSpec = {
  title: 'MUDemy API Guide',
  version: '1.0',
  notes: 'Auth uses cookie `session_id` set by POST /login. Roles: `tutor`, `tutee`, `admin`.',
  groups: [

    /* =====================
       routes_login.py
       Authentication
       ===================== */
    {
      group: 'routes_login.py',
      description: 'Authentication endpoints. Successful login sets `session_id` cookie (httponly).',
      routes: [
        {
          name: 'List Roles',
          method: 'GET',
          path: '/roles',
          auth: 'none',
          roles: ['any'],
          input: null,
          output: {
            type: 'array',
            items: { id: 'string', label: 'string', description: 'string' }
          },
          examples: {
            request: null,
            response: [
              { id: 'TUTOR', label: 'tutor', description: 'Dành cho giảng viên' },
              { id: 'TUTEE', label: 'tutee', description: 'Dành cho học viên' },
              { id: 'ADMIN', label: 'admin', description: 'Quản trị hệ thống' }
            ]
          }
        },

        {
          name: 'Login',
          method: 'POST',
          path: '/login',
          auth: 'none',
          roles: ['any'],
          input: {
            body: {
              username: 'string (User_name from USER table)',
              password: 'string',
              role: "'tutor' | 'tutee' | 'admin'"
            }
          },
          output: {
            username: 'string',
            role: 'string',
            status: 'string'
          },
          examples: {
            request: { username: 'USR00006', password: 'P@ssw0rd!', role: 'tutee' },
            response: { username: 'USR00006', role: 'tutee', status: 'Login successful' }
          }
        },

        {
          name: 'Logout',
          method: 'POST',
          path: '/logout',
          auth: 'cookie',
          roles: ['any'],
          input: null,
          output: { status: 'Logout successful' },
          examples: { request: null, response: { status: 'Logout successful' } }
        }
      ]
    },


    /* =====================
       routes_user.py
       Users, Takes, Interests, Instruct, Qualifications
       ===================== */
    {
      group: 'routes_user.py',
      description: 'User CRUD and helper endpoints. See `USER`, `TAKE`, `INTERESTS`, `INSTRUCT`, `QUALIFICATION` tables in DDL/models.',
      routes: [

        {
          name: 'Get current user',
          method: 'GET',
          path: '/users/me',
          auth: 'cookie',
          roles: ['any'],
          input: null,
          output: {
            status: 'string',
            user: {
              UserID: 'string',
              User_name: 'string',
              Email: 'string?',
              Full_name: 'string?'
            }
          },
          examples: { response: { status: 'success', user: { UserID: 'USR00006', User_name: 'tuanti', Full_name: 'Nguyen Tuan' } } }
        },

        {
          name: 'Create user',
          method: 'POST',
          path: '/users',
          auth: 'none',
          roles: ['any'],
          input: {
            body: {
              User_name: 'string (required, unique, NVARCHAR(100))',
              Email: 'string (required, unique, check format)',
              Password: 'string (required, min 6, mixed chars required by DDL checks)',
              Full_name: 'string (optional)',
              City: 'string (optional)',
              Country: 'string (optional)',
              Phone: 'string (optional)',
              Date_of_birth: 'YYYY-MM-DD (optional)',
              IFlag: 'boolean (optional) - instructor flag',
              SFlag: 'boolean (optional) - student flag'
            }
          },
          output: { status: 'created', user_id: 'string (UserID auto-generated by trigger if not provided)' },
          examples: {
            request: { User_name: 'alice', Email: 'alice@example.com', Password: 'Str0ng#Pass', Full_name: 'Alice Example', SFlag: true },
            response: { status: 'created', user_id: 'USR00014' }
          }
        },

        {
          name: 'List users',
          method: 'GET',
          path: '/users',
          auth: 'cookie',
          roles: ['tutor','admin'],
          input: { query: { limit: 'int (default 100)' } },
          output: { status: 'success', count: 'int', users: [{ UserID: 'string', User_name: 'string', Full_name: 'string' }] },
          examples: { response: { status: 'success', count: 10 } }
        },

        {
          name: 'Get user by id',
          method: 'GET',
          path: '/users/{user_id}',
          auth: 'cookie',
          roles: ['owner|tutor|admin'],
          input: { path: { user_id: 'string' } },
          output: { status: 'success', user: { UserID: 'string', User_name: 'string', Email: 'string', Full_name: 'string' } },
          examples: { response: { status: 'success', user: { UserID: 'USR00006', User_name: 'tuanti', Email: 't@example.com', Full_name: 'Nguyen Tuan' } } }
        },

        {
          name: 'Update user',
          method: 'PUT',
          path: '/users/{user_id}',
          auth: 'cookie',
          roles: ['owner|admin|tutor'],
          input: { path: { user_id: 'string' }, body: { Full_name: 'string?', City: 'string?', Country: 'string?', Phone: 'string?', Bio_text: 'string?' } },
          output: { status: 'updated', user_id: 'string' },
          examples: { request: { Full_name: 'Updated Name' }, response: { status: 'updated', user_id: 'USR00006' } }
        },

        {
          name: 'Delete user',
          method: 'DELETE',
          path: '/users/{user_id}',
          auth: 'cookie',
          roles: ['tutor','admin'],
          input: { path: { user_id: 'string' } },
          output: { status: 'deleted', user_id: 'string' },
          examples: { response: { status: 'deleted', user_id: 'USR00006' } }
        },

        /* Takes (lesson progress) */
        {
          name: 'Create take (lesson progress)',
          method: 'POST',
          path: '/takes',
          auth: 'cookie',
          roles: ['tutee'],
          input: { body: { UserID: 'string', LessonID: 'string', is_finished: 'boolean (optional, default false)' } },
          output: { status: 'created', UserID: 'string', LessonID: 'string' },
          examples: { request: { UserID: 'USR00006', LessonID: 'L001', is_finished: false }, response: { status: 'created', UserID: 'USR00006', LessonID: 'L001' } }
        },

        {
          name: 'Get take (user + lesson)',
          method: 'GET',
          path: '/takes/{user_id}/{lesson_id}',
          auth: 'cookie',
          roles: ['owner|tutor|admin'],
          input: { path: { user_id: 'string', lesson_id: 'string' } },
          output: { status: 'success', take: { UserID: 'string', LessonID: 'string', is_finished: 'boolean' } },
          examples: { response: { status: 'success', take: { UserID: 'USR00006', LessonID: 'L001', is_finished: false } } }
        },

        {
          name: 'Get lesson progress (summary)',
          method: 'GET',
          path: '/takes/{user_id}/progress',
          auth: 'cookie',
          roles: ['owner|tutor|admin'],
          input: { path: { user_id: 'string' } },
          output: { status: 'success', progress: { total_lessons: 'int', completed_lessons: 'int', completion_rate: 'float (percent)' } },
          examples: { response: { status: 'success', progress: { total_lessons: 10, completed_lessons: 6, completion_rate: 60.0 } } }
        },

        /* Interests */
        {
          name: 'Add interest',
          method: 'POST',
          path: '/users/{user_id}/interests',
          auth: 'cookie',
          roles: ['owner|tutor|admin'],
          input: { body: { Interest: 'string' } },
          output: { status: 'created', UserID: 'string', Interest: 'string' },
          examples: { request: { Interest: 'Python' }, response: { status: 'created', user_id: 'USR00006', interest: 'Python' } }
        },

        /* Instruct */
        {
          name: 'Assign instructor to course',
          method: 'POST',
          path: '/instruct',
          auth: 'cookie',
          roles: ['tutor','admin'],
          input: { body: { UserID: 'string', CourseID: 'string' } },
          output: { status: 'assigned', UserID: 'string', CourseID: 'string' },
          examples: { request: { UserID: 'USR00001', CourseID: 'CRS00001' }, response: { status: 'assigned', UserID: 'USR00001', CourseID: 'CRS00001' } }
        },

        /* Qualifications */
        {
          name: 'Add qualification',
          method: 'POST',
          path: '/users/{user_id}/qualifications',
          auth: 'cookie',
          roles: ['tutor','admin'],
          input: { body: { Qualification: 'string' } },
          output: { status: 'created', UserID: 'string', Qualification: 'string' },
          examples: { request: { Qualification: 'PhD in CS' }, response: { status: 'created', user_id: 'USR00001' } }
        }

      ]
    },


    /* =====================
       routes_course.py
       Course, Module, Content, Category, Requires
       ===================== */
    {
      group: 'routes_course.py',
      description: 'Course, module and content management endpoints. Fields follow COURSE, MODULE, CONTENT tables.',
      routes: [

        {
          name: 'List courses',
          method: 'GET',
          path: '/courses',
          auth: 'cookie',
          roles: ['any'],
          input: { query: { skip: 'int', limit: 'int', difficulty: "'Beginner'|'Intermediate'|'Advanced' (optional)" } },
          output: { status: 'success', count: 'int', courses: [{ CourseID: 'string', Title: 'string', Difficulty: 'string' }] },
          examples: { response: { status: 'success', count: 6 } }
        },

        {
          name: 'Create course',
          method: 'POST',
          path: '/courses',
          auth: 'cookie',
          roles: ['tutor','admin'],
          input: { body: { Title: 'string (min 5)', Language: 'string', Difficulty: "'Beginner'|'Intermediate'|'Advanced' (optional)", Description: 'string (optional)' } },
          output: { status: 'created', CourseID: 'string' },
          examples: { request: { Title: 'Data Science 101', Language: 'English', Difficulty: 'Beginner' }, response: { status: 'created', course_id: 'CRS00007' } }
        },

        {
          name: 'Add category to course',
          method: 'POST',
          path: '/courses/{course_id}/categories',
          auth: 'cookie',
          roles: ['tutor','admin'],
          input: { body: { Category: 'string' } },
          output: { status: 'created', CourseID: 'string', Category: 'string' },
          examples: { request: { Category: 'Data Science' }, response: { status: 'created' } }
        },

        {
          name: 'Add prerequisite',
          method: 'POST',
          path: '/courses/{course_id}/prerequisites',
          auth: 'cookie',
          roles: ['tutor','admin'],
          input: { body: { Required_courseID: 'string' } },
          output: { status: 'created', CourseID: 'string', Required_courseID: 'string' },
          examples: { request: { Required_courseID: 'CRS00002' }, response: { status: 'created', CourseID: 'CRS00003', Required_courseID: 'CRS00002' } }
        }

      ]
    },


    /* =====================
       routes_assessment.py
       Assignments, Quizzes, Questions, Answers, Submissions
       ===================== */
    {
      group: 'routes_assessment.py',
      description: 'Assessment endpoints. Uses ASSIGNMENT, QUIZ, QUESTION, ANSWER, ASSIGN_SUBMISSION, QUIZ_SUBMISSION models.',
      routes: [

        {
          name: 'Create assignment',
          method: 'POST',
          path: '/assignments',
          auth: 'cookie',
          roles: ['tutor','admin'],
          input: { body: { Title: 'string', ModuleID: 'string', Deadline: 'ISO datetime', Description: 'string (optional)' } },
          output: { status: 'created', AssID: 'string' },
          examples: { request: { Title: 'HW1', ModuleID: 'MOD001', Deadline: '2025-12-01T23:59:00' }, response: { status: 'created', assignment_id: 'ASS0001' } }
        },

        {
          name: 'Create quiz',
          method: 'POST',
          path: '/quizzes',
          auth: 'cookie',
          roles: ['tutor','admin'],
          input: { body: { Title: 'string', ModuleID: 'string', Time_limit: 'int (seconds)', Num_attempt: 'int', Deadline: 'ISO datetime' } },
          output: { status: 'created', QuizID: 'string' },
          examples: { request: { Title: 'Quiz 1', ModuleID: 'MOD001', Time_limit: 900 }, response: { status: 'created', quiz_id: 'QUIZ001' } }
        },

        {
          name: 'Create question',
          method: 'POST',
          path: '/quizzes/{quiz_id}/questions',
          auth: 'cookie',
          roles: ['tutor','admin'],
          input: { body: { Content: 'string', Correct_answer: 'string (can be NVARCHAR(MAX))' } },
          output: { status: 'created', QuestionID: 'string' },
          examples: { request: { Content: 'What is 2+2?', Correct_answer: '4' }, response: { status: 'created', QuestionID: 'QST001' } }
        },

        {
          name: 'Create answer',
          method: 'POST',
          path: '/questions/{question_id}/answers',
          auth: 'cookie',
          roles: ['tutor','admin'],
          input: { body: { QuizID: 'string', Answer: 'string' } },
          output: { status: 'created', AnswerID: 'string' },
          examples: { request: { QuizID: 'QUIZ001', Answer: '4' }, response: { status: 'created', AnswerID: 'ANS001' } }
        },

        {
          name: 'Submit assignment',
          method: 'POST',
          path: '/assignments/{ass_id}/submit',
          auth: 'cookie',
          roles: ['tutee'],
          input: { body: { UserID: 'string (optional)', Sub_content: 'string (text or file-link)', Sub_date: 'ISO datetime (optional)' } },
          output: { status: 'created', SubID: 'string' },
          examples: { request: { Sub_content: 'Answer file link' }, response: { status: 'created', SubID: 'SUB001' } }
        },

        {
          name: 'Get latest assignment submissions (one per student)',
          method: 'GET',
          path: '/assignments/{ass_id}/submissions/latest',
          auth: 'cookie',
          roles: ['tutor','admin'],
          input: { path: { ass_id: 'string' } },
          output: { status: 'success', submissions: [{ SubID: 'string', UserID: 'string', Grade: 'number?', Sub_date: 'ISO datetime' }] },
          examples: { response: { status: 'success', submissions: [ { SubID: 'SUB101', UserID: 'USR00006', Grade: 85.0, Sub_date: '2025-11-30T10:00:00' } ] } }
        },

        {
          name: 'Get latest quiz submissions (one per student)',
          method: 'GET',
          path: '/quizzes/{quiz_id}/submissions/latest',
          auth: 'cookie',
          roles: ['tutor','admin'],
          input: { path: { quiz_id: 'string' } },
          output: { status: 'success', submissions: [{ SubID: 'string', UserID: 'string', Grade: 'number?', Sub_date: 'ISO datetime' }] },
          examples: { response: { status: 'success', submissions: [ { SubID: 'QSUB050', UserID: 'USR00006', Grade: 80.0, Sub_date: '2025-11-30T12:34:00' } ] } }
        },

        {
          name: 'Module quiz stats (stored proc GetQuizPerformanceStats)',
          method: 'GET',
          path: '/modules/{module_id}/quiz-stats',
          auth: 'cookie',
          roles: ['tutor','admin'],
          input: { query: { module_id: 'string (path)', min_submissions: 'int (default 1)' } },
          output: { status: 'success', rows: [{ QuizID: 'string', AvgScore: 'number', NumSubmissions: 'int' }] },
          examples: { response: { status: 'success', rows: [ { QuizID: 'QUIZ001', AvgScore: 78.25, NumSubmissions: 12 } ] } }
        }

      ]
    },


    /* =====================
       routes_enrollment.py
       Enrollment, Payment, Certificate
       ===================== */
    {
      group: 'routes_enrollment.py',
      description: 'Enrollment, payment and certificate endpoints. See ENROLLMENT, PAYMENT, CERTIFICATE tables in DDL/models.',
      routes: [

        {
          name: 'Create enrollment',
          method: 'POST',
          path: '/enroll',
          auth: 'cookie',
          roles: ['tutee'],
          input: { body: { CourseID: 'string', PaymentID: 'string', StudentID: 'string (optional, defaults to current user)' } },
          output: { status: 'created', EnrollmentID: 'string' },
          examples: { request: { CourseID: 'CRS00001', PaymentID: 'PAY0001' }, response: { status: 'created', enrollment_id: 'ENR0001' } }
        },

        {
          name: 'Create payment',
          method: 'POST',
          path: '/payments',
          auth: 'cookie',
          roles: ['tutor','tutee','admin'],
          input: { body: { Amount: 'int (>=0)', Payment_method: "enum('Credit Card','Debit Card','PayPal','Bank Transfer','Cash')", UserID: 'string (optional)' } },
          output: { status: 'created', PaymentID: 'string' },
          examples: { request: { Amount: 200, Payment_method: 'Credit Card' }, response: { status: 'created', payment_id: 'PAY0001' } }
        },

        {
          name: 'Create certificate',
          method: 'POST',
          path: '/certificates',
          auth: 'cookie',
          roles: ['tutor','admin'],
          input: { body: { CourseID: 'string', StudentID: 'string', Certificate_number: 'string', Expiry_date: 'YYYY-MM-DD (optional)' } },
          output: { status: 'created', CertificateID: 'string' },
          examples: { request: { CourseID: 'CRS00001', StudentID: 'USR00006', Certificate_number: 'CERT-2025-0001' }, response: { status: 'created', certificate_id: 'CERT001' } }
        }

      ]
    },


    /* =====================
       routes_resource.py
       RESOURCE and PROVIDE_RESOURCE
       ===================== */
    {
      group: 'routes_resource.py',
      description: 'Resource CRUD and ProvideResource (lesson->resource) mapping endpoints. Follows RESOURCE and PROVIDE_RESOURCE tables.',
      routes: [

        {
          name: 'Create resource',
          method: 'POST',
          path: '/resources',
          auth: 'cookie',
          roles: ['tutor','admin'],
          input: { body: { File_Name: 'string (required)', File_link: 'string (required)', External_link: 'string (optional)' } },
          output: { status: 'created', ResourceID: 'string' },
          examples: { request: { File_Name: 'slides.pdf', File_link: 'https://cdn.example/slides.pdf' }, response: { status: 'created', resource_id: 'RES001' } }
        },

        {
          name: 'Get resource',
          method: 'GET',
          path: '/resources/{resource_id}',
          auth: 'cookie',
          roles: ['any'],
          input: { path: { resource_id: 'string' } },
          output: { status: 'success', resource: { ResourceID: 'string', File_Name: 'string', File_link: 'string', External_link: 'string?' } },
          examples: { response: { status: 'success', resource: { ResourceID: 'RES001', File_Name: 'slides.pdf', File_link: 'https://cdn.example/slides.pdf' } } }
        },

        {
          name: 'Provide resource to lesson',
          method: 'POST',
          path: '/provide',
          auth: 'cookie',
          roles: ['tutor','admin'],
          input: { body: { ResourceID: 'string', LessonID: 'string' } },
          output: { status: 'provided', ResourceID: 'string', LessonID: 'string' },
          examples: { request: { ResourceID: 'RES001', LessonID: 'L001' }, response: { status: 'provided', ResourceID: 'RES001', LessonID: 'L001' } }
        }

      ]
    },


    /* =====================
       routes_utils.py
       health / root
       ===================== */
    {
      group: 'routes_utils.py',
      description: 'Health-check and root message.',
      routes: [
        { name: 'Health check', method: 'GET', path: '/health', auth: 'none', input: null, output: { status: 'ok' }, examples: { response: { status: 'ok' } } },
        { name: 'Root', method: 'GET', path: '/', auth: 'none', input: null, output: { message: 'string' }, examples: { response: { message: 'Backend is up and running. Navigate to ./docs for Swagger contents' } } }
      ]
    }

  ]
};

export default apiSpec;
